export const CHANNEL_SET_CURRENT = 'CHANNEL_SET_CURRENT';
export const CHANNEL_DELETE = 'CHANNEL_DELETE';
export const CHANNEL_ADD = 'CHANNEL_ADD';

export const MESSAGE_DELETE_CHANNEL = 'MESSAGE_DELETE_CHANNEL';
export const MESSAGE_DELETE = 'MESSAGE_DELETE';
export const MESSAGE_ADD = 'MESSAGE_ADD';
export const MESSAGE_EDIT = 'MESSAGE_EDIT';


